# Generated by Django 4.1.5 on 2023-02-21 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cl_ITSM_USER',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ch_email', models.EmailField(max_length=254)),
                ('ch_login', models.CharField(max_length=100, null=True)),
                ('ch_language', models.CharField(max_length=100, null=True)),
                ('ch_status', models.CharField(max_length=100, null=True)),
                ('ch_password', models.CharField(max_length=100, null=True)),
                ('ch_password_expiration', models.CharField(max_length=100, null=True)),
                ('dt_password_renewed_on', models.DateTimeField()),
                ('ch_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.cl_person')),
            ],
            options={
                'db_table': 'cl_ITSM_USER',
            },
        ),
        migrations.DeleteModel(
            name='ch_Itsmuser',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cl_googlechat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cl_itsmwebhook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cl_rocketchat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='csv_import',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='email_notifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sms_notifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tassign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 10, 24, 25, 78815)),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
