# Generated by Django 3.2.12 on 2023-01-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_new_change',
            name='ch_assign_agent',
            field=models.CharField(default='Deallocated', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cl_person',
            name='ch_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.cl_team'),
        ),
    ]
