# Generated by Django 4.1.6 on 2023-03-21 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 10, 9, 37, 783915)),
        ),
        migrations.AlterModelTable(
            name='cl_hardware',
            table='cl_Hardware',
        ),
    ]
