# Generated by Django 4.1.3 on 2023-01-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cl_network_device',
            old_name='i_os_version',
            new_name='i_ios_version',
        ),
    ]
