# Generated by Django 3.2.12 on 2023-01-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_user_request',
            name='dt_escalation_date',
        ),
    ]
