# Generated by Django 4.1.5 on 2023-01-25 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_activity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=200)),
                ('resultcode', models.IntegerField()),
                ('duration', models.DateTimeField(default=datetime.datetime(2023, 1, 25, 0, 5, 4, 627422))),
            ],
            options={
                'db_table': 'user_activity_log',
            },
        ),
    ]
