# Generated by Django 4.1.3 on 2023-02-15 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_user_request',
            name='ch_status',
            field=models.CharField(default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 14, 49, 19, 266102)),
        ),
    ]
