# Generated by Django 4.1.3 on 2023-02-22 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_cl_itsm_user_delete_ch_itsmuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='boat_notifier',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('boat_id', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'boat_notifier',
            },
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 10, 4, 48, 850173)),
        ),
    ]
