# Generated by Django 4.1.5 on 2023-02-03 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_remove_adminuser_ch_user_expirydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='approval',
            field=models.CharField(default='off', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='assign',
            field=models.CharField(default='off', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 10, 3, 16, 513640)),
        ),
    ]
