# Generated by Django 4.1.6 on 2023-02-09 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_person',
            name='ch_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.cl_person'),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 14, 21, 8, 76653)),
        ),
    ]
