# Generated by Django 3.2.12 on 2023-01-13 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_remove_cl_user_request_dt_escalation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_user_request',
            name='dt_escalation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
