# Generated by Django 4.1.5 on 2023-01-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_cl_brand_id_alter_cl_ios_version_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_new_change',
            name='ch_caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.cl_person'),
        ),
    ]
