# Generated by Django 4.1.5 on 2023-01-31 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_remove_adminuser_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 14, 27, 43, 72953)),
        ),
    ]
