# Generated by Django 4.1.3 on 2023-03-01 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_adminuser_first_name_alter_adminuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cl_Reopen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_reopen', models.TextField()),
            ],
            options={
                'db_table': 'cl_Reopen',
            },
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 12, 15, 22, 653141)),
        ),
    ]
