# Generated by Django 4.1.3 on 2023-02-13 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_cl_user_request_dt_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cl_user_request',
            old_name='dt_updated_date',
            new_name='dt_Updated_date',
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 11, 22, 32, 87637)),
        ),
    ]
