# Generated by Django 4.1.6 on 2023-02-23 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_user_request',
            name='ch_service_tto_slts',
        ),
        migrations.RemoveField(
            model_name='cl_user_request',
            name='ch_service_ttr_slts',
        ),
        migrations.RemoveField(
            model_name='cl_user_request',
            name='dt_TTO_escalation_date',
        ),
        migrations.RemoveField(
            model_name='cl_user_request',
            name='dt_TTR_escalation_date',
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 14, 23, 22, 810466)),
        ),
    ]
