# Generated by Django 4.1.6 on 2023-03-15 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='cl_Resolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_resolved', models.TextField()),
                ('ureq_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cl_Resolved',
            },
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 16, 48, 40, 267554)),
        ),
    ]
