# Generated by Django 4.1.5 on 2023-02-03 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_roles_approval_roles_assign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='assign',
        ),
        migrations.AddField(
            model_name='roles',
            name='ch_m_approve',
            field=models.CharField(default='off', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='ch_m_assign',
            field=models.CharField(default='off', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='inci_m_approve',
            field=models.CharField(default='off', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='inci_m_assign',
            field=models.CharField(default='off', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 10, 52, 0, 583825)),
        ),
    ]
