# Generated by Django 4.1.3 on 2023-03-01 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_cl_reopen_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_user_request',
            name='reopen_reason',
            field=models.TextField(default='issue'),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 15, 50, 16, 932073)),
        ),
    ]
