# Generated by Django 4.1.6 on 2023-02-14 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_cl_service_subcategory_ch_sla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_service',
            name='ch_service_family',
        ),
        migrations.AddField(
            model_name='cl_service',
            name='ch_service_subcategory',
            field=models.ManyToManyField(to='tool.cl_service_subcategory'),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 11, 30, 7, 838635)),
        ),
    ]
