# Generated by Django 3.2.12 on 2023-01-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_cl_new_change_ch_assign_agent_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_new_change',
            name='ch_assign_agent_emp_id',
        ),
    ]
