# Generated by Django 4.1.5 on 2023-01-31 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_remove_adminuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 14, 28, 54, 43763)),
        ),
    ]
