# Generated by Django 4.1.5 on 2023-01-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_rename_i_os_version_cl_network_device_i_ios_version'),
        ('tool', '0003_cl_user_request_dt_escalation_date'),
    ]

    operations = [
    ]
