# Generated by Django 4.1.3 on 2023-02-22 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_boat_notifier_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 12, 20, 33, 987683)),
        ),
    ]
