# Generated by Django 4.1.6 on 2023-03-06 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='ch_user_mobilenumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 9, 42, 3, 486511)),
        ),
    ]
