# Generated by Django 4.1.3 on 2023-03-02 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_cl_user_request_reopen_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_reopen',
            name='cm_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cl_reopen',
            name='cm_txt_reopen',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cl_reopen',
            name='ur_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 16, 13, 24, 271315)),
        ),
    ]
