# Generated by Django 3.2.12 on 2023-01-10 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_remove_cl_new_change_ch_assign_agent_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_new_change',
            name='dt_end_date',
        ),
        migrations.AddField(
            model_name='cl_new_change',
            name='dt_Updated_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cl_new_change',
            name='dt_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
