# Generated by Django 4.1.6 on 2023-02-09 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_alter_cl_person_id_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_person',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 15, 33, 2, 692625)),
        ),
    ]
