# Generated by Django 4.1.5 on 2023-01-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_merge_20230119_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_location',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
