# Generated by Django 4.1.3 on 2023-02-22 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat_notifier',
            old_name='boat_id',
            new_name='boat_tokan',
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 12, 25, 42, 24880)),
        ),
    ]
