# Generated by Django 4.1.6 on 2023-03-16 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_cl_resolved_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='cl_CReopen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_creopen', models.TextField()),
                ('creq_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cl_CReopen',
            },
        ),
        migrations.CreateModel(
            name='cl_CResolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_cresolved', models.TextField()),
                ('creq_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cl_CResolved',
            },
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 11, 1, 56, 16596)),
        ),
    ]
