# Generated by Django 4.1.6 on 2023-02-14 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_remove_cl_service_ch_service_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 11, 45, 27, 225922)),
        ),
    ]
