# Generated by Django 4.1.3 on 2023-02-22 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_rename_boat_id_boat_notifier_boat_tokan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cl_person',
            old_name='ch_person_phone',
            new_name='telegram_chatid',
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 12, 37, 10, 114828)),
        ),
    ]
