# Generated by Django 4.1.3 on 2023-03-02 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_cl_reopen_cm_id_cl_reopen_cm_txt_reopen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cl_reopen',
            old_name='cm_id',
            new_name='cmng_id',
        ),
        migrations.RenameField(
            model_name='cl_reopen',
            old_name='ur_id',
            new_name='ureq_id',
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 16, 16, 8, 796188)),
        ),
    ]
