# Generated by Django 4.1.3 on 2023-01-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_rename_ch_agent_cl_user_request_ch_assign_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_user_request',
            name='dt_start_date',
            field=models.DateTimeField(),
        ),
    ]
