# Generated by Django 4.1.6 on 2023-02-14 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_providercontract',
            name='dt_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cl_providercontract',
            name='dt_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 15, 14, 40, 926128)),
        ),
    ]
