# Generated by Django 4.1.3 on 2023-03-02 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_rename_cm_id_cl_reopen_cmng_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_reopen',
            name='cm_txt_reopen',
        ),
        migrations.RemoveField(
            model_name='cl_reopen',
            name='cmng_id',
        ),
        migrations.AlterField(
            model_name='cl_reopen',
            name='ureq_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 16, 45, 4, 838762)),
        ),
    ]
