# Generated by Django 4.1.6 on 2023-03-10 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_alter_adminuser_ch_user_mobilenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_person',
            name='ch_manager',
        ),
        migrations.AddField(
            model_name='cl_team',
            name='L1_Manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L1_Manager', to='tool.cl_person'),
        ),
        migrations.AddField(
            model_name='cl_team',
            name='L2_Manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='L2_Manager', to='tool.cl_person'),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 12, 22, 30, 907691)),
        ),
    ]
