# Generated by Django 4.1.6 on 2023-02-14 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_alter_cl_providercontract_dt_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cl_providercontract',
            name='ch_sla',
        ),
        migrations.AddField(
            model_name='cl_providercontract',
            name='ch_services',
            field=models.ManyToManyField(to='tool.cl_service'),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 15, 51, 34, 964175)),
        ),
    ]
