# Generated by Django 4.1.6 on 2023-03-10 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_remove_cl_person_ch_manager_cl_team_l1_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 12, 25, 51, 973224)),
        ),
    ]
