# Generated by Django 4.1.6 on 2023-02-14 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_remove_cl_providercontract_ch_sla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 16, 6, 4, 874570)),
        ),
    ]
