# Generated by Django 4.1.6 on 2023-02-15 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_alter_user_activity_log_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_customer_contract',
            name='ch_services',
            field=models.ManyToManyField(to='tool.cl_service'),
        ),
        migrations.AlterField(
            model_name='cl_customer_contract',
            name='dt_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cl_customer_contract',
            name='dt_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 9, 55, 17, 778974)),
        ),
    ]
