# Generated by Django 4.1.6 on 2023-02-15 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_cl_customer_contract_ch_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_customer_contract',
            name='i_cost_currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cl_providercontract',
            name='i_cost_currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_activity_log',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 11, 36, 36, 375875)),
        ),
    ]
